import './globals.css';

import { Geist, Geist_Mono } from 'next/font/google';

import { EmotionRegistry } from '@lib/EmotionRegistry';
import type { Metadata } from 'next';
import ThemeProviders from '@lib/ThemeProviders';
import localFont from 'next/font/local';

// export const suitFont = localFont({
//   src: [
//     {
//       path: '../public/fonts/SUIT-Variable.woff2',
//       // path: './src/fonts/SUIT-Variable.woff2',
//       style: 'normal',
//     },
//   ],
//   variable: '--font-suit',
//   display: 'swap',
// });
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        // className={suitFont.variable}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <body className={`${geistSans.variable} ${geistMono.variable} ${suitFont.variable} antialiased`}> */}
        <EmotionRegistry>
          <ThemeProviders>{children}</ThemeProviders>
        </EmotionRegistry>
      </body>
    </html>
  );
}
